apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-dep
  template:
    metadata:
      labels:
        app: app-dep
    spec:
      containers:
        - name: app-dep
          image: ${ECR_REGISTRY}/${JOB_NAME}:${IMAGE_TG}
          ports:
            - containerPort: 8080
