apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-dep-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: app-dep
spec:
  groups:
    - name: app-dep.rules
      rules:
        - alert: MyAppTargetDown
          expr: up{job="app-service"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "app-dep target down ({{ $labels.instance }})"
            description: "Prometheus has not been able to scrape {{ $labels.instance }} for more than 2 minutes."

        - alert: MyAppPodRestartingFrequently
          expr: increase(kube_pod_container_status_restarts_total{namespace="monitoring", pod=~"app-dep-.*"}[15m]) > 3
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "app-dep pod restarting frequently ({{ $labels.pod }})"
            description: "{{ $labels.pod }} has restarted more than 3 times in the last 15 minutes."

        - alert: MyAppReplicasMismatch
          expr: kube_deployment_status_replicas_available{deployment="app-dep", namespace="monitoring"} < kube_deployment_spec_replicas{deployment="myapp", namespace="monitoring"}
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "myapp has fewer available replicas than desired"
            description: "Deployment myapp has {{ $value }} available replicas, below the desired count."
